version: '3.8'

services:
  sitecheck:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY:?OPENAI_API_KEY is required}
    ports:
      - "${PORT:-8001}:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:?OPENAI_API_KEY is required}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}  # Optional
      - PYTHONPATH=/app
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8001}
      - COLLECTION_NAME=${COLLECTION_NAME:-sitecheck}
      - VECTORDB_PATH=${VECTORDB_PATH:-/app/vectordb}
    env_file:
      - .env
    volumes:
      - ./agentforge:/app/agentforge
      - vectordb:/app/vectordb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
        reservations:
          memory: 1G
          cpus: '0.5'
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  vectordb:
    name: sitecheck-vectordb 